/*----------------------------------------------------------------------------*/
#ifndef naprH
#define naprH

#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <ToolWin.hpp>
#include <Buttons.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>
#include <vector.h>
#include "structures.h"

using namespace std;
using namespace ExData;
/*----------------------------------------------------------------------------*/
// структура визуальных компонентов
/*----------------------------------------------------------------------------*/
struct TVisualDirection{
  TPanel *pnl;
  TComboBox *cdPort;
  TComboBox *cdCol;
  TComboBox *cdDk;
  TCheckBox *chkCtn;
  TShape *round;
  TLabel *text;
  };
/*----------------------------------------------------------------------------*/
class TfrmDirection : public TForm
{
__published:	// IDE-managed Components
        TPanel *Panel1;
        TToolBar *ToolBar1;
        TButton *btnClose;
        TBitBtn *btnPlus;
        TBitBtn *BitBtn2;
        TSplitter *Splitter1;
        TButton *btnOk;
        TStatusBar *StatusBar1;
        TSplitter *Splitter2;
        TScrollBox *scrlbxDirection;
        TPanel *pnlR1;
        TLabel *Label4;
        TShape *shpR1;
        TComboBox *cbbGroupR1;
        TComboBox *cbbCollorR1;
        TCheckBox *chkR1;
        TPanel *pnlY1;
        TLabel *Label5;
        TShape *shpY1;
        TComboBox *cbbGroupY11;
        TComboBox *cbbCollorY11;
        TCheckBox *chkY11;
        TComboBox *cbbDkY11;
        TPanel *pnlG1;
        TLabel *Label7;
        TShape *shpG1;
        TComboBox *cbbGroupG11;
        TComboBox *cbbCollorG11;
        TCheckBox *chkG11;
        TComboBox *cbbDkG11;
        TListBox *lstOut;
        TSplitter *spl;
        TPanel *pnlY11;
        TLabel *Label16;
        TShape *shpY11;
        TComboBox *cbbGroupY32;
        TComboBox *cbbCollorY32;
        TCheckBox *chkY32;
        TComboBox *cbbDkY32;
        TPanel *pnlR11;
        TLabel *Label17;
        TShape *shpR11;
        TComboBox *cbbGroupR32;
        TComboBox *cbbCollorR32;
        TCheckBox *chkR32;
        TComboBox *cbbDkR32;
        TPanel *pnlG11;
        TLabel *Label18;
        TShape *shpG11;
        TComboBox *cbbGroupG32;
        TComboBox *cbbCollorG32;
        TCheckBox *chkG32;
        TComboBox *cbbDkG32;
        TPanel *pnlY3;
        TLabel *Label19;
        TShape *shpY3;
        TComboBox *cbbGroupY31;
        TComboBox *cbbCollorY31;
        TCheckBox *chkY31;
        TComboBox *cbbDkY31;
        TPanel *pnlR3;
        TLabel *Label20;
        TShape *shpR3;
        TComboBox *cbbGroupR3;
        TComboBox *cbbCollorR3;
        TCheckBox *chkR3;
        TComboBox *cbbDkR3;
        TPanel *pnlG3;
        TLabel *Label21;
        TShape *shpG3;
        TComboBox *cbbGroupG31;
        TComboBox *cbbCollorG31;
        TCheckBox *chkG31;
        TComboBox *cbbDkG31;
        TPanel *pnlY12;
        TLabel *Label22;
        TShape *shpY12;
        TComboBox *cbbGroupY42;
        TComboBox *cbbCollorY42;
        TCheckBox *chkY42;
        TComboBox *cbbDkY42;
        TPanel *pnlR12;
        TLabel *Label23;
        TShape *shpR12;
        TComboBox *cbbGroupR42;
        TComboBox *cbbCollorR42;
        TCheckBox *chkR42;
        TComboBox *cbbDkR42;
        TPanel *pnlG12;
        TLabel *Label24;
        TShape *shpG12;
        TComboBox *cbbGroupG42;
        TComboBox *cbbCollorG42;
        TCheckBox *chkG42;
        TComboBox *cbbDkG42;
        TPanel *pnlY4;
        TLabel *Label25;
        TShape *shpY4;
        TComboBox *cbbGroupY41;
        TComboBox *cbbCollorY41;
        TCheckBox *chkY41;
        TComboBox *cbbDkY41;
        TPanel *pnlR4;
        TLabel *Label26;
        TShape *shpR4;
        TComboBox *cbbGroupR4;
        TComboBox *cbbCollorR4;
        TCheckBox *chkR4;
        TComboBox *cbbDkR4;
        TPanel *pnlG4;
        TLabel *Label27;
        TShape *shpG4;
        TComboBox *cbbGroupG41;
        TComboBox *cbbCollorG41;
        TCheckBox *chkG41;
        TComboBox *cbbDkG41;
        TPanel *pnlY13;
        TLabel *Label28;
        TShape *shpY13;
        TComboBox *cbbGroupY52;
        TComboBox *cbbCollorY52;
        TCheckBox *chkY52;
        TComboBox *cbbDkY52;
        TPanel *pnlR13;
        TLabel *Label29;
        TShape *shpR13;
        TComboBox *cbbGroupR52;
        TComboBox *cbbCollorR52;
        TCheckBox *chkR52;
        TComboBox *cbbDkR52;
        TPanel *pnlG13;
        TLabel *Label30;
        TShape *shpG13;
        TComboBox *cbbGroupG52;
        TComboBox *cbbCollorG52;
        TCheckBox *chkG52;
        TComboBox *cbbDkG52;
        TPanel *pnlY5;
        TLabel *Label31;
        TShape *shpY5;
        TComboBox *cbbGroupY51;
        TComboBox *cbbCollorY51;
        TCheckBox *chkY51;
        TComboBox *cbbDkY51;
        TPanel *pnlR5;
        TLabel *Label32;
        TShape *shpR5;
        TComboBox *cbbGroupR5;
        TComboBox *cbbCollorR5;
        TCheckBox *chkR5;
        TComboBox *cbbDkR5;
        TPanel *pnlG5;
        TLabel *Label33;
        TShape *shpG5;
        TComboBox *cbbGroupG51;
        TComboBox *cbbCollorG51;
        TCheckBox *chkG51;
        TComboBox *cbbDkG51;
        TPanel *pnlY14;
        TLabel *Label34;
        TShape *shpY14;
        TComboBox *cbbGroupY62;
        TComboBox *cbbCollorY62;
        TCheckBox *chkY62;
        TComboBox *cbbDkY62;
        TPanel *pnlR14;
        TLabel *Label35;
        TShape *shpR14;
        TComboBox *cbbGroupR62;
        TComboBox *cbbCollorR62;
        TCheckBox *chkR62;
        TComboBox *cbbDkR62;
        TPanel *pnlG14;
        TLabel *Label36;
        TShape *shpG14;
        TComboBox *cbbGroupG62;
        TComboBox *cbbCollorG62;
        TCheckBox *chkG62;
        TComboBox *cbbDkG62;
        TPanel *pnlY6;
        TLabel *Label37;
        TShape *shpY6;
        TComboBox *cbbGroupY61;
        TComboBox *cbbCollorY61;
        TCheckBox *chkY61;
        TComboBox *cbbDkY61;
        TPanel *pnlR6;
        TLabel *Label38;
        TShape *shpR6;
        TComboBox *cbbGroupR6;
        TComboBox *cbbCollorR6;
        TCheckBox *chkR6;
        TComboBox *cbbDkR6;
        TPanel *pnlG6;
        TLabel *Label39;
        TShape *shpG6;
        TComboBox *cbbGroupG61;
        TComboBox *cbbCollorG61;
        TCheckBox *chkG61;
        TComboBox *cbbDkG61;
        TPanel *pnlY15;
        TLabel *Label40;
        TShape *shpY15;
        TComboBox *cbbGroupY72;
        TComboBox *cbbCollorY72;
        TCheckBox *chkY72;
        TComboBox *cbbDkY72;
        TPanel *pnlR15;
        TLabel *Label41;
        TShape *shpR15;
        TComboBox *cbbGroupR72;
        TComboBox *cbbCollorR72;
        TCheckBox *chkR72;
        TComboBox *cbbDkR72;
        TPanel *pnlG15;
        TLabel *Label42;
        TShape *shpG15;
        TComboBox *cbbGroupG72;
        TComboBox *cbbCollorG72;
        TCheckBox *chkG72;
        TComboBox *cbbDkG72;
        TPanel *pnlY7;
        TLabel *Label43;
        TShape *shpY7;
        TComboBox *cbbGroupY71;
        TComboBox *cbbCollorY71;
        TCheckBox *chkY71;
        TComboBox *cbbDkY71;
        TPanel *pnlR7;
        TLabel *Label44;
        TShape *shpR7;
        TComboBox *cbbGroupR7;
        TComboBox *cbbCollorR7;
        TCheckBox *chkR7;
        TComboBox *cbbDkR7;
        TPanel *pnlG7;
        TLabel *Label45;
        TShape *shpG7;
        TComboBox *cbbGroupG71;
        TComboBox *cbbCollorG71;
        TCheckBox *chkG71;
        TComboBox *cbbDkG71;
        TPanel *pnlY16;
        TLabel *Label46;
        TShape *shpY16;
        TComboBox *cbbGroupY82;
        TComboBox *cbbCollorY82;
        TCheckBox *chkY82;
        TComboBox *cbbDkY82;
        TPanel *pnlR16;
        TLabel *Label47;
        TShape *shpR16;
        TComboBox *cbbGroupR82;
        TComboBox *cbbCollorR82;
        TCheckBox *chkR82;
        TComboBox *cbbDkR82;
        TPanel *pnlG16;
        TLabel *Label48;
        TShape *shpG16;
        TComboBox *cbbGroupG82;
        TComboBox *cbbCollorG82;
        TCheckBox *chkG82;
        TComboBox *cbbDkG82;
        TPanel *pnlY8;
        TLabel *Label49;
        TShape *shpY8;
        TComboBox *cbbGroupY81;
        TComboBox *cbbCollorY81;
        TCheckBox *chkY81;
        TComboBox *cbbDkY81;
        TPanel *pnlR8;
        TLabel *Label50;
        TShape *shpR8;
        TComboBox *cbbGroupR8;
        TComboBox *cbbCollorR8;
        TCheckBox *chkR8;
        TComboBox *cbbDkR8;
        TPanel *pnlG8;
        TLabel *Label51;
        TShape *shpG8;
        TComboBox *cbbGroupG81;
        TComboBox *cbbCollorG81;
        TCheckBox *chkG81;
        TComboBox *cbbDkG81;
        TPanel *pnlY9;
        TLabel *Label1;
        TShape *shpY9;
        TComboBox *cbbGroupY12;
        TComboBox *cbbCollorY12;
        TCheckBox *chkY12;
        TComboBox *cbbDkY12;
        TPanel *pnlR9;
        TLabel *Label2;
        TShape *shpR9;
        TComboBox *cbbGroupR12;
        TComboBox *cbbCollorR12;
        TCheckBox *chkR12;
        TComboBox *cbbDkR12;
        TPanel *pnlG9;
        TLabel *Label3;
        TShape *shpG9;
        TComboBox *cbbGroupG12;
        TComboBox *cbbCollorG12;
        TCheckBox *chkG12;
        TComboBox *cbbDkG12;
        TPanel *pnlY2;
        TLabel *Label6;
        TShape *shpY2;
        TComboBox *cbbGroupY21;
        TComboBox *cbbCollorY21;
        TCheckBox *chkY21;
        TComboBox *cbbDkY21;
        TPanel *pnlR2;
        TLabel *Label8;
        TShape *shpR2;
        TComboBox *cbbGroupR2;
        TComboBox *cbbCollorR2;
        TCheckBox *chkR2;
        TComboBox *cbbDkR2;
        TPanel *pnlG2;
        TLabel *Label9;
        TShape *shpG2;
        TComboBox *cbbGroupG21;
        TComboBox *cbbCollorG21;
        TCheckBox *chkG21;
        TComboBox *cbbDkG21;
        TPanel *pnlY10;
        TLabel *Label10;
        TShape *shpY10;
        TComboBox *cbbGroupY22;
        TComboBox *cbbCollorY22;
        TCheckBox *chkY22;
        TComboBox *cbbDkY22;
        TPanel *pnlR10;
        TLabel *Label11;
        TShape *shpR10;
        TComboBox *cbbGroupR22;
        TComboBox *cbbCollorR22;
        TCheckBox *chkR22;
        TComboBox *cbbDkR22;
        TPanel *pnlG10;
        TLabel *Label12;
        TShape *shpG10;
        TComboBox *cbbGroupG22;
        TComboBox *cbbCollorG22;
        TCheckBox *chkG22;
        TComboBox *cbbDkG22;
        TComboBox *cbbDkR1;
        TPanel *pnlPlus;
        TPanel *Panel19;
        TListBox *lstPanelPlus;
        TPanel *Panel20;
        TPanel *pnlPlusOk;
        TPanel *pnlPlusExit;
        TLabel *lblR1;
        TLabel *lblR2;
        TLabel *lblR3;
        TLabel *lblR4;
        TLabel *lblR5;
        TLabel *lblR6;
        TLabel *lblR7;
        TLabel *lblR8;
        TLabel *lblR9;
        TLabel *lblR10;
        TLabel *lblR11;
        TLabel *lblR12;
        TLabel *lblR13;
        TLabel *lblR14;
        TLabel *lblR15;
        TLabel *lblR16;
        TLabel *lblY1;
        TLabel *lblY2;
        TLabel *lblY3;
        TLabel *lblY4;
        TLabel *lblY5;
        TLabel *lblY6;
        TLabel *lblY7;
        TLabel *lblY8;
        TLabel *lblY9;
        TLabel *lblY10;
        TLabel *lblY11;
        TLabel *lblY12;
        TLabel *lblY13;
        TLabel *lblY14;
        TLabel *lblY15;
        TLabel *lblY16;
        TLabel *lblG1;
        TLabel *lblG2;
        TLabel *lblG3;
        TLabel *lblG4;
        TLabel *lblG5;
        TLabel *lblG6;
        TLabel *lblG7;
        TLabel *lblG8;
        TLabel *lblG9;
        TLabel *lblG10;
        TLabel *lblG11;
        TLabel *lblG12;
        TLabel *lblG13;
        TLabel *lblG14;
        TLabel *lblG15;
        TLabel *lblG16;

        void __fastcall FormCreate(TObject *Sender);
        void __fastcall btnPlusClick(TObject *Sender);
        void __fastcall Panel5Click(TObject *Sender);
        void __fastcall Panel6Click(TObject *Sender);
        void __fastcall BitBtn2Click(TObject *Sender);
        void __fastcall btnCloseClick(TObject *Sender);
        void __fastcall btnOkClick(TObject *Sender);
        void __fastcall FormDestroy(TObject *Sender);
        void __fastcall cbbChangePORT(TObject *Sender);
        void __fastcall cbbChangeCOLOR(TObject *Sender);
        void __fastcall cbbChangeDK(TObject *Sender);
        void __fastcall cbClickCONTR(TObject *Sender);
        void __fastcall lstOutClick(TObject *Sender);
private:	// User declarations
        enum DIR_IN{RED_IN = 0,YEL_IN=16,GREN_IN=32};
        std::vector<TVisualDirection*> visDirectionRed;
        std::vector<TVisualDirection*> visDirectionYellow;
        std::vector<TVisualDirection*> visDirectionGreen;
        TStringList *strCCG;
        TStringList *strUDZCG;
        TStringList *strClorCCG;
        TStringList *strClorUDZCG;
        TPROJECT   tempPrg; //копия проекта
        TONEDIRECT tempOneDirection; // рабочие направление
        int     curDirect; // текущее создаваемое направление
        void StatusBar(AnsiString txt);
        void showTypeDir(const bool type);
        void showNumDk(const int number);
        void showNumPort(const int maxNumBlock);
        void showListDirection(void);
        void setListDirection(void);
        void addListDirection(void);
        bool setParametrOneDirectoin(const int currentDirection);
        bool showParametrOneDirectoin(const int currentDirection);
        bool checkDataToShow(const int currentDirection);
        //bool checkAllSructParametr(void);
        void clearDataofChange(TPROJECT *prg);
        int  getDk(const int tag);
        int  getGroup(const int tag);
        int  getColor(const int tag);
        bool checkOneSructureCurrentDirection(const WORD Dir,const WORD Color,const WORD Dk,const WORD Tag);
        bool checkOneSructParametr(const WORD Group,const WORD Color,const WORD Dk);
        bool checkSructParametrDK(const TComboBox *cmb);
        bool checkSructParametrGroup(const TComboBox *cmb);
        bool checkSructParametrColor(const TComboBox *cmb);
public:		// User declarations
        __fastcall TfrmDirection(TComponent* Owner);
        void ShowMainFormDirection(TPROJECT *prg);
};
/*----------------------------------------------------------------------------*/
extern PACKAGE TfrmDirection *frmDirection;

#endif
